config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  resources :items do
    patch :complete, on: :member
  end

  get '/cobrowse', to: 'cobrowse#new'
  post '/cobrowse', to: 'cobrowse#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cobrowse_controller.rb
class CobrowseController < ApplicationController
  before_action :authenticate

  def new
    @agent_name = @username.split('@').first.capitalize
  end

  def create
    result = UpscopeSessionService.new(upscope_params).perform

    render json: { watch_url: result.watch_url, message: result.message }
  end

  private

  def upscope_params
    params.require(:upscope_session).permit(:lookup_code, :agent_name, :agent_email)
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      if username.match(/[a-zA-Z0-9]+@acme.com/) && password == Rails.application.credentials[:acme_password]
        @username = username
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy, :complete]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def edit; end

  def update
    @item.update(item_params)

    redirect_to root_path, notice: 'Item has been updated'
  end

  def create
    @item = Item.new(item_params)

    @item.save

    redirect_to root_path, notice: 'New Item was added successfully'
  end

  def destroy
    @item.destroy

    redirect_to root_path, notice: 'Item has been deleted'
  end

  def complete
    @item.update(completed: true)

    redirect_to root_path, notice: 'Item has been completed'
  end

  private

  def set_item
    @item = Item.find params[:id]
  end

  def item_params
    params.require(:item).permit(:description, :due_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cobrowse/new.html.erb
<%= form_for :upscope_session, url: cobrowse_path, method: :post do |f| %>
  <%= f.hidden_field :agent_name, value: @agent_name %>
  <%= f.hidden_field :agent_email, value: @username %>

  <div class="form-group">
    <div class="row">
      <div class="col-md-4">
        <%= f.label :lookup_code %>
        <%= f.text_field :lookup_code, class: 'form-control' %>
        <div class="invalid-feedback"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :due_date, "Due Date" %>
    <%= f.date_field :due_date, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>
  <%= link_to "Back", :back, class: 'btn btn-default' %>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <td>Description</td>
      <td>Due Date</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr class="item-<%= item.id %>">
        <td><%= item.description %></td>
        <td><%= item.due_date %></td>
        <td>
          <% unless item.completed %>
            <div class="btn-group btn-group-sm" role="group">
              <%= link_to 'Complete', complete_item_path(item), class: 'btn btn-success', method: :patch %>
              <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-primary' %>
              <%= link_to 'Delete', item_path(item), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if notice %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <%= yield %>

      <%= link_to 'Co-browsing code', '#', class: 'upscope-link' %>
    </div>

    <script>
      (function(w, u, d){var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};var l = function(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://code.upscope.io/4vpK14DAPB.js';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);};if(typeof u!=="function"){w.Upscope=i;l();}})(window, window.Upscope, document);

      Upscope('init', {});

      Upscope('on', 'sessionStart', 'sessionContinue', (e) => {
        const link = document.querySelector('.upscope-link')

        link.style.display = 'none'
      })

      Upscope('on', 'sessionEnd', (e) => {
        const link = document.querySelector('.upscope-link')

        link.style.display = 'block'
      })
    </script>
  </body>
</html>